export const routes = {
  MAIN: '/',
  BASKET: '/basket',
  CATEGORY: '/category',
  CATEGORY_SLUG: '/category/[slug]',
  CHAT: '/chat',
  CHECKOUT: '/checkout',
  CHECKOUT_SUCCESS: '/checkout/success/[slug]',
  DOCS: '/docs',
  FAVORITE: '/favorite',
  ORDERS: '/orders',
  PRODUCT: '/product',
  PROFILE: '/profile',
  REVIEWS: '/reviews',
  SEARCH: '/search',
  SHOP: '/shop',
  SHOP_SLUG: '/shop/[slug]',
  OFFER: '/offer',
  AFFILIATE: '/affiliate',
  PARTNER: '/partner',
  BRAND: '/brand',
  BRAND_SLUG: '/brand/[slug]'
}
